/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import civitas.CivitasJuego;
import javax.swing.JOptionPane;
import civitas.Casilla;
import civitas.Diario;
import civitas.OperacionInmobiliaria;
import civitas.OperacionJuego;
import controladorCivitas.Respuesta;
import java.util.ArrayList;
import java.util.Arrays;
/**
 *
 * @author josev
 */
public class CivitasView extends javax.swing.JFrame {
    CivitasJuego juego;
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        infoCasilla = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        siguienteOperacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ranking = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setText("CIVITAS");

        jLabel1.setText("Info Casilla :");

        infoCasilla.setEditable(false);
        infoCasilla.setText("jTextField1");

        jLabel2.setText("Siguiente Operación :");

        siguienteOperacion.setEditable(false);
        siguienteOperacion.setText("jTextField1");
        siguienteOperacion.setBorder(null);

        jLabel3.setText("RANKING");

        ranking.setEditable(false);
        ranking.setColumns(20);
        ranking.setRows(5);
        ranking.setBorder(null);
        jScrollPane1.setViewportView(ranking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(titulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGap(508, 508, 508)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(siguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(siguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setCivitasJuego(CivitasJuego juego){
        this.juego = juego;
        this.setVisible(true);
        this.jLabel3.setVisible(false);
        this.ranking.setVisible(false);
        siguienteOperacion.setVisible(false);
    }
    
    public void actualiza(){
        jugadorPanel1.setJugador(juego.getJugadorActual());
        
        Casilla casillaActual = juego.getTablero().getCasilla(juego.getJugadorActual().getCasillaActual());
        infoCasilla.setText(casillaActual.toString());
        
        if(juego.finalDelJuego() == true){
            ranking.setText(juego.ranking());
            this.jLabel3.setVisible(true);
            ranking.setVisible(true); 
        }
        repaint();
        revalidate();
        //Actualiza el panel de info del jugador en curso
    }

     public void pausa(){
        int val= JOptionPane.showConfirmDialog(null, "¿Continuar?","Siguiente paso", JOptionPane.YES_NO_OPTION);
        if (val==1) System.exit(0);
        
 }

    public Respuesta comprar(){
        int val = 1-JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?", "Compra", JOptionPane.YES_NO_OPTION);
        if(val == 1) return Respuesta.SI;
        else return Respuesta.NO;
    }

    public OperacionInmobiliaria elegirOperacion(){
        GestionarDialog gestion = new GestionarDialog(this, true);
        int operacionARealizar = gestion.getGestionElegida();
        switch (operacionARealizar) {
            case 0:
                return OperacionInmobiliaria.CONSTRUIR_CASA;
            case 1:
                return OperacionInmobiliaria.CONSTRUIR_HOTEL;
            default:
                return OperacionInmobiliaria.TERMINAR;
        }
    }

    public int elegirPropiedad(){
        PropiedadDialog propiedadDialog = new PropiedadDialog(this, true, juego.getJugadorActual());
        return propiedadDialog.getPropiedadElegida();
    }

    public void mostrarSiguienteOperacion(OperacionJuego operacion){
        
        siguienteOperacion.setText(operacion.name());
        siguienteOperacion.setVisible(true);
        if(operacion == OperacionJuego.AVANZAR){
            Dado.createInstance(this);
        }
        
        repaint();
    }

    public void mostrarEventos(){
        if (!Diario.getInstance().getEventos().isEmpty()){
            DiarioDialog diarioD= new DiarioDialog(this, true); //Crea la ventana de diario
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField infoCasilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ranking;
    private javax.swing.JTextField siguienteOperacion;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
