/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import civitas.Jugador;
import java.util.ArrayList;
import civitas.CasillaCalle;
/**
 *
 * @author josev
 */
public class JugadorPanel extends javax.swing.JPanel {
    
    public Jugador jugador;
    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }
        
    public void setJugador(Jugador jugador){
        this.jugador = jugador;
        
        this.nombre.setText(this.jugador.getNombre());
        this.saldo.setText(String.valueOf(this.jugador.getSaldo())); //Uso el metodo toString de la clase float para la conversion
        this.esEspeculador.setText(String.valueOf(this.jugador.esEspeculador()));
        
        rellenaPropiedades(this.jugador.getPropiedades());
        
        repaint();
        revalidate();
    }
    
    private void rellenaPropiedades (ArrayList<CasillaCalle> lista) {
        // Se elimina la información antigua
        propiedadesPanel.removeAll();
        // Se recorre la lista de propiedades para ir creando sus vistas individuales y añadirlas al panel
        for (CasillaCalle t : lista) {
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);

            propiedadesPanel.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        
        // Se fuerza la actualización visual del panel propiedades y del panel del jugador
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        saldo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        esEspeculador = new javax.swing.JTextField();
        propiedadesPanel = new javax.swing.JPanel();

        jLabel1.setText("NOMBRE :");
        add(jLabel1);

        nombre.setEditable(false);
        nombre.setText("jTextField1");
        add(nombre);

        jLabel2.setText("SALDO :");
        add(jLabel2);

        saldo.setEditable(false);
        saldo.setText("jTextField1");
        add(saldo);

        jLabel3.setText("ESPECULADOR :");
        add(jLabel3);

        esEspeculador.setEditable(false);
        esEspeculador.setText("jTextField1");
        add(esEspeculador);

        propiedadesPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(propiedadesPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField esEspeculador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel propiedadesPanel;
    private javax.swing.JTextField saldo;
    // End of variables declaration//GEN-END:variables
}
